### ISSUE TITLE
Private App road map

### ISSUE THREAD

**Issue by hdoupe** [compute-tooling/compute-studio#304]
This issue outlines the plan for adding private apps:

- [ ] 1. Make files in cloud storage private and run all downloads through C/S authentication. Currently, they are behind UUID file names and are quasi private. However, if apps are private for data sensitivity purposes, then the files should be fully private.
  - [ ] Zip files should be made private (this should have little to no affect on users since the file downloads are routed through the C/S webserver)
  - [ ] Screenshots of outputs should be made private. This is the only _direct_ link to the storage bucket that is hit by users. One thing to think about is what this will mean for performance on the initial load of the simulation page.
- [ ] 2. Port access management from `Simulation` model to `Project` model. This should be straightforward, but will require moving over and testing the model methods for managing access and the API endpoints that expose control of them to the user.
- [ ] 3. Adapt Collaborator UI elements to work with simulations and models. I intend the API endpoints and flow to be similar, except maybe for the author concept. 

cc @peter-metz @MattHJensen
